model:
  target: Models.interpretable_diffusion.gaussian_diffusion.Diffusion_TS
  params:
    seq_length: 34
    feature_size: 5
    n_layer_enc: 2
    n_layer_dec: 2
    d_model: 128  
    timesteps: 1000
    sampling_timesteps: 500
    loss_type: 'l1'
    beta_schedule: 'cosine'
    n_heads: 4
    mlp_hidden_times: 4
    attn_pd: 0.0
    resid_pd: 0.0
    kernel_size: 1
    padding_size: 0



solver:
  base_lr: 1.0e-5
  max_epochs: 15000
  results_folder: '/content/drive/MyDrive/Masterthesis/Data/Sequences/crossAsset/crossAsset'
  gradient_accumulate_every: 2
  save_cycle:  1000
  ema:
    decay: 0.995
    update_interval: 10
  
  scheduler:
    target: engine.lr_sch.ReduceLROnPlateauWithWarmup
    params:
      factor: 0.5
      patience: 2000
      min_lr: 1.0e-5
      threshold: 1.0e-1
      threshold_mode: rel
      warmup_lr: 8.0e-4
      warmup: 500 
      verbose: False

dataloader:
  train_dataset:
    target: Utils.Data_utils.real_dataset_guided_diffusion.CustomDatasetGuided
    params:
      data_root: '/content/drive/MyDrive/Masterthesis/Data/Datasets/crossAsset_portfolio.csv'
      window: 34  # seq_length
      end: 5298
      save2npy: True
      neg_one_to_one: True
      period: train

  



  batch_size: 64
  sample_size: 256
  shuffle: True